ALTER TABLE admin_profile ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE admin_profile ADD COLUMN IF NOT EXISTS province TEXT DEFAULT '';
ALTER TABLE admin_profile ADD COLUMN IF NOT EXISTS city TEXT DEFAULT '';
ALTER TABLE admin_profile ADD COLUMN IF NOT EXISTS extra_emails TEXT[] DEFAULT '{}';
